version: '3.1'
services:
  stats-server:
    build: stats/stats-service
    image: stats-service
    container_name: stats-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/hit
      - stats-server.uri=http://stats-server:9090

  stats-db:
    image: postgres:14.6-alpine
    container_name: stats_db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=hit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ./ewm-service
    image: ewm-service
    container_name: ewm_service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - STATS-SERVER_URL=http://stat-server:9090

  ewm-db:
    image: postgres:14.6-alpine
    container_name: ewm_db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root